version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ws_server"
    schedule:
      interval: "weekly"
    target-branch: "master"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/master_server"
    schedule:
      interval: "weekly"
    target-branch: "master"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
